### ISSUE TITLE
Installation error: "cannot load such file -- haml (LoadError)"

### ISSUE THREAD

**Issue by phacks** [prettier/plugin-haml#2] opened 2020-11-12 18:01 UTC
Hey!

First off, thank you so much for this plugin, as it makes developing in HAML a breeze.

I opened this issue because I encountered several problems during installation, some of them I don’t really know where they come from. I managed to hack my way through to a solution, which I will post here also in case it helps someone else out there.

**Implicit `haml` requirement**

This line

https://github.com/prettier/plugin-haml/blob/92760679425fa6bd009f1c5f31d53b4831f5db68/src/parser.rb#L4

is an implicit requirement on the `haml` gem. That raised the following error at runtime in VSCode:

```
`require': cannot load such file -- haml (LoadError)
```

As this plugin is supposed to, well, work with haml, one could think that the requirement will always be fulfilled. However that was not the case for me. That brings me to my second issue.

**VSCode is not using my `rbenv` version of ruby**

The VSCode stacktrace was mentioning the following path for Ruby when using this plugin `/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby`, which is the OSX default one and _not_ the one used by my shell, development environment or otherwise as all of those are managed by rbenv.

I don’t know why that is, but that’s the reason why `haml` wasn’t installed (as I never use the system version of ruby).

The (admittedly dirty) fix to my issue was then to run the following command:

```
sudo /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/gem install haml
```

I think finding a way to have the plugin use the “correct” path to ruby for rbenv users would solve all this.

Feel free to close this issue if it is out of scope of the plugin (I don’t have a clue what’s going on. Otherwise, I’d be happy to help in any way I can!

**Comment by kddnewton** [comment] 2020-11-12 21:30
Yeah so unfortunately this is kind of out of scope of this plugin. The issue is you need the `haml` gem installed and you need it to be within the Ruby `$LOAD_PATH` global variable. This could be accomplished through `rbenv`, `rvm`, `chruby`, or just your system install. It's going to depend on each person' individual setup. 

You're going to want to look into VSCode's configuration options or how to specify which ruby you should be using. Once you get the right ruby configured, it'll have the right gems installed and it should work from there.

**Closed as completed by kddnewton** 2020-11-12 21:30 UTC
